config/routes.rb
Rails.application.routes.draw do

  root 'events#home'

    resources :users
    resources :events
    resources :organizations

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events, inverse_of: :users
  has_many :organizations
  has_secure_password

  validates :first_name, presence: true, length: {minimum: 2}
  validates :last_name, presence: true, length: {minimum: 2}
  validates :email, uniqueness: true
  validates :password, presence: true, confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  def home
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :url, :start_date, :end_date)
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.fetch(:organization, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.slim
.row
  .large-6.columns
    = form_for @event do |f|
      - if @event.errors.any?
        #error_explanation
          h2 = "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
          ul
            - @event.errors.full_messages.each do |message|
              li = message

      = f.text_field :name
      = f.text_area :description
      = f.url_field :url
      = f.date_field :start_date
      = f.date_field :end_date

      .actions = f.submit

app/views/events/edit.html.slim
h1 Editing event

== render 'form'

= link_to 'Show', @event
'|
= link_to 'Back', events_path

app/views/events/home.html.slim
h1 Busy Giver

p I want to
  <select>
    <option value="default">do anything</option>
    <option value="Eat">Eat</option>
  </select>

| for good in

  <select>
    <option value="default">the world</option>
    <option value="default">Raleigh</option>
  </select>
      
table
  thead
    tr
      th Name
      th Description
      th URL
      th start_date
      th end_date

  tbody
    - @events.each do |event|
      tr
        td = event.name
        td = event.description
        td = event.url
        td = event.start_date
        td = event.end_date

app/views/events/index.html.slim
h1 Listing events

table
  thead
    tr
      th Name
      th Description
      th URL
      th start_date
      th end_date
      th
      th
      th

  tbody
    - @events.each do |event|
      tr
        td = event.name
        td = event.description
        td = event.url
        td = event.start_date
        td = event.end_date
        td = link_to 'Show', event
        td = link_to 'Edit', edit_event_path(event)
        td = link_to 'Destroy', event, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Event', new_event_path

app/views/events/new.html.slim
h1 New event

== render 'form'

= link_to 'Back', events_path

app/views/events/show.html.slim
p#notice = notice


= link_to 'Edit', edit_event_path(@event)
'|
= link_to 'Back', events_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Busy Giver
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .row
      .large-12.columns
        = yield    

app/views/organizations/_form.html.slim
= form_for @organization do |f|
  - if @organization.errors.any?
    #error_explanation
      h2 = "#{pluralize(@organization.errors.count, "error")} prohibited this organization from being saved:"
      ul
        - @organization.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/organizations/edit.html.slim
h1 Editing organization

== render 'form'

= link_to 'Show', @organization
'|
= link_to 'Back', organizations_path

app/views/organizations/index.html.slim
h1 Listing organizations

table
  thead
    tr
      th
      th
      th

  tbody
    - @organizations.each do |organization|
      tr
        td = link_to 'Show', organization
        td = link_to 'Edit', edit_organization_path(organization)
        td = link_to 'Destroy', organization, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Organization', new_organization_path

app/views/organizations/new.html.slim
h1 New organization

== render 'form'

= link_to 'Back', organizations_path

app/views/organizations/show.html.slim
p#notice = notice


= link_to 'Edit', edit_organization_path(@organization)
'|
= link_to 'Back', organizations_path

app/views/users/_form.html.slim
.row
  .large-6.columns
    = form_for @user do |f|
      - if @user.errors.any?
        #error_explanation
          h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
          ul
            - @user.errors.full_messages.each do |message|
              li = message

      = f.text_field :first_name
      = f.text_field :last_name
      = f.email_field :email
      = f.password_field :password, :null => false, :default => ""
      = f.password_field :password_confirmation, :null => false, :default => ""
      .actions = f.submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th id
      th First Name
      th Last Name
      th Email
      th Joined
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.id
        td = user.first_name
        td = user.last_name
        td = user.email
        td = user.created_at
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

table
  thead
    th id
    th First Name
    th Last Name
    th Email
    th Password
    th Created At
  tbody
    tr
      td = @user.id
      td = @user.first_name
      td = @user.last_name
      td = @user.email
      td = @user.password_digest
      td = @user.created_at

= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path